COMPASS-3113: Checkpoint on refactor evg config
Making headway. Continue with https://github.com/evergreen-ci/evergreen/wiki/Project-Files as ref

diff --git a/.evergreen.yml b/.evergreen.yml
--- a/.evergreen.yml
+++ b/.evergreen.yml
@@ -15,12 +15,13 @@ exec_timeout_secs: 1800
 #            Functions                #
 #######################################
 functions:
-  'configure':
+  'prepare':
     command: shell.exec
     params:
       working_dir: src
       script: |
-        set -ev
+        set -e
+
         cat <<EOF_BUILD_SH > ~/compass_env.sh
         export PATH="${node_path}:$PATH"
         export APPDATA=${add_env_appdata}
@@ -28,7 +29,7 @@ functions:
         export EVERGREEN=1
 
         # Tweak as needed for more or less debugging output in logs
-        export DEBUG="hadron*,electron*,mongodb-notary-service*";
+        # export DEBUG="hadron*,electron*,mongodb-notary-service*";
 
         # Make default evergreen expansions accessible to hadron-build
         export EVERGREEN_ASSET_PREFIX="s3://mciuploads/${project}/${revision}";
@@ -62,51 +63,168 @@ functions:
         export DOWNLOAD_CENTER_AWS_SECRET_ACCESS_KEY=${aws_secret_evergreen_integrations}
         EOF_BUILD_SH
 
+  # 'install node.js':
+  #   command: shell.exec
+  #     params:
+  #       working_dir: src
+  #       script: |
+  #         mkdir -p .deps
+  #         set -e
+
+  #         # Get precompiled
+  #         curl -fs \
+  #           -o ".deps/${fetch_npm_tarball}" \
+  #           --url "https://nodejs.org/download/release/v8.9.3/${fetch_npm_tarball}"
+  #         cd .deps
+  #         tar xzf ${fetch_npm_tarball} --strip-components=1
+
+  #         ls -alh
+
+  #         rm -f npm npx npm.cmd npx.cmd
+  #         mv lib/node_modules/npm lib/node_modules/npm2
+
+  #         chmod +x ./bin/node
+  #         ./bin/node lib/node_modules/npm2/bin/npm-cli.js i -g npm@latest
+  #         rm -rf lib/node_modules/npm2/
+
+  # 'install node.js windows':
+  #   command: shell.exec
+  #     params:
+  #       working_dir: src
+  #       script: |
+  #         mkdir -p .deps
+  #         set -e
+  #         # is node already installed?
+  #         npm version || true
+
+  #         # Get precompiled
+  #         curl -fs \
+  #           -o ".deps/node-v8.9.3-win-x64.zip" \
+  #           --url "https://nodejs.org/download/release/v8.9.3/node-v8.9.3-win-x64.zip"
+  #         cd .deps
+  #         unzip node-v8.9.3-win-x64.zip
+  #         mv node-v8.9.3-win-x64/* .
+  #         rm -rf node-v8.9.3-win-x64
+
+  #         export PATH="${node_path}:$PATH"
+  #         export APPDATA=${add_env_appdata}
+
+  #         ls -alh
+
+  #         rm -rf npm npx npm.cmd npx.cmd
+  #         mv node_modules/npm node_modules/npm2
+  #         ls -alh
+
+  #         chmod +x ./node.exe
+
+  #         ./node.exe node_modules/npm2/bin/npm-cli.js i -g npm@latest
+  #         rm -rf node_modules/npm2/
+  #         chmod +x npm.cmd
+  #         chmod +x npm
+
+  #         ./npm.cmd version
+
+  #         curl -fs \
+  #           -o "signtool.exe" \
+  #           --url "https://s3.amazonaws.com/boxes.10gen.com/build/signtool.exe"
+  #         rm -f node_modules/electron-winstaller/vendor/signtool.exe
+  #         chmod +x signtool.exe
+
   'install':
-    command: shell.exec
-    params:
-      working_dir: src
-      script: |
-        set -ev
+    - command: shell.exec
+      params:
+        working_dir: src
+        script: |
+          set -e
+          # Load environment variables generated by `configure`
+          . ~/compass_env.sh
+
+          echo "Configure npm"
+          # TODO (imlucas) npm configuration should all happen in one place.
+          # This could all be done by environment variables.
+          echo "//registry.npmjs.org/:_authToken=${compass_npm_token}" >> .npmrc
+          # npm config list -l
+          echo "Trying to get rid of scandir npm errors."
+          echo "<timer task=install.npm.cache_verify_and_clean>"
+          npm cache verify
+          npm cache -f clean
+          echo "</timer>"
+    - command: shell.exec
+      params:
+        working_dir: src
+        script: |
+        set -e
         # Load environment variables generated by `configure`
         . ~/compass_env.sh
-        echo "//registry.npmjs.org/:_authToken=${compass_npm_token}" >> .npmrc
-
-        # Trying to get rid of scandir npm errors.
-        npm cache verify
-        npm cache -f clean
-
+        echo "<timer install.npm.install>"
         npm install
-        npm run evergreen-expansions ${compass_distribution}
-        cat expansions.yml
+        echo "</timer>"
+    - command: shell.exec
+      params:
+        working_dir: src
+        script: |
+          set -e
+          # Load environment variables generated by `configure`
+          . ~/compass_env.sh
 
-  'build':
+          echo "<timer install.evergreen_expansions>"
+          npm run evergreen-expansions ${compass_distribution}
+          echo "</timer>"
+    - command: expansions.update
+      params:
+        file: src/expansions.yml
+  
+  'verify':
     command: shell.exec
     params:
       working_dir: src
       script: |
-        set -ev
-        cat <<EOF_BUILD_SH > ~/compass_build.sh
-        cd $(pwd)
+        set -e
+
         # Load environment variables
         . ~/compass_env.sh
 
-        # Run static analysis on code and project configuration
+        echo "Run static analysis on code and project configuration"
+        echo "<timer task=verify>"
         npm run check;
-        # Run tests
-        npm test;
+        echo "</timer>"
 
-        # Create a release build
+  'test':
+    command: shell.exec
+    params:
+      working_dir: src
+      script: |
+        set -e
+
+        # Load environment variables
+        . ~/compass_env.sh
+        echo "NOTE (imlucas) Making this a noop for now, but leaving the func for future reference"
+        # echo "Run tests"
+        # echo "<timer task=test>"
+        # npm test;
+        # echo "</timer>"
+
+  'package':
+    command: shell.exec
+    params:
+      working_dir: src
+      script: |
+        set -e
+        cat <<EOF_BUILD_SH > ~/compass_build.sh
+        cd $(pwd)
+
+        # Load environment variables
+        . ~/compass_env.sh
+
+        echo "Create signed a release build"
+        echo "<timer task=package>"
         npm run release ${compass_distribution};
-        ls -alh dist || true;
-
-        # Upload release assets to S3 and GitHub
-        npm run upload ${compass_distribution}
+        echo "</timer>"
         EOF_BUILD_SH
 
-        #
-        # Use ".", not "source" below to read script. Required for /bin/sh on Ubuntu.
-        #
+        # NOTE (imlucas) This build_via_local_tunnel thing is needed for
+        # codesign to work on the macOS box. Can't remember but something
+        # related to keychain unlock? Go look it up.
         if [ -n "${build_via_local_tunnel|}" ]
         then
           ssh -v -p 2222 localhost ". compass_build.sh"
@@ -114,17 +232,24 @@ functions:
           . ~/compass_build.sh
         fi
 
-  'test_ssh_localhost':
+  'publish':
     command: shell.exec
     params:
       working_dir: src
       script: |
-        set -ev
-        if [ -n "${build_via_local_tunnel|}" ]
-        then
-          ssh -p 2222 localhost "echo SSH_LOCALHOST_TEST_OK"
-        fi
+        set -e
 
+        # Load environment variables
+        . ~/compass_env.sh
+
+        echo "Upload release assets to S3 and GitHub if needed"
+        echo "<timer task=publish>"
+        npm run upload ${compass_distribution}
+        echo "</timer>"
+
+  # NOTE (@imlucas) A ton of this can go away... use the generate tasks and stuff from migrator.
+  # The actual uploads can be handled by `hadron-build` to S3 and then use
+  # the `attach.results` evergreen command to show links on this page.
   'save windows artifacts':
     # setup
     - command: s3.put
@@ -257,13 +382,12 @@ functions:
 #######################################
 #               Tasks                 #
 #######################################
-
 pre:
   - command: shell.exec
     params:
       silent: true
       script: |
-        set -ev
+        set -e
         rm -rf src /data/db/*
         mkdir -p src
 
@@ -271,42 +395,38 @@ tasks:
   - name: compile
     depends_on: []
     commands:
-      - func: 'test_ssh_localhost'
-        variants:
-          - macos-compass
-          - macos-compass-community
-          - macos-compass-readonly
-          - macos-compass-isolated
       - command: git.get_project
         params:
           directory: src
-      - command: git.apply_patch
-        params:
-          directory: src
+      # TODO (imlucas) git.apply_patch is deprecated. Patches are applied in git.get_project.
+      # - command: git.apply_patch
+      #   params:
+      #     directory: src
       - command: shell.exec
         params:
           working_dir: src
           script: |
+            set -e
             mkdir -p .deps
-            set -ev
-            # is node already installed?
-            npm version || true
 
+            echo "<timer task=bootstrap.node.pull>"
             # Get precompiled
             curl -fs \
               -o ".deps/${fetch_npm_tarball}" \
               --url "https://nodejs.org/download/release/v8.9.3/${fetch_npm_tarball}"
             cd .deps
             tar xzf ${fetch_npm_tarball} --strip-components=1
+            echo "</timer>"
 
-            ls -alh
 
+            echo "<timer task=bootstrap.update_npm>"
             rm -f npm npx npm.cmd npx.cmd
             mv lib/node_modules/npm lib/node_modules/npm2
 
             chmod +x ./bin/node
-            ./bin/node lib/node_modules/npm2/bin/npm-cli.js i -g npm@5.7.1
+            ./bin/node lib/node_modules/npm2/bin/npm-cli.js i -g npm@latest
             rm -rf lib/node_modules/npm2/
+            echo "</timer>"
 
         variants:
           - macos-compass
@@ -326,7 +446,7 @@ tasks:
           working_dir: src
           script: |
             mkdir -p .deps
-            set -ev
+            set -e
             # is node already installed?
             npm version || true
 
@@ -350,27 +470,19 @@ tasks:
 
             chmod +x ./node.exe
 
-            ./node.exe node_modules/npm2/bin/npm-cli.js i -g npm@5.7.1
+            ./node.exe node_modules/npm2/bin/npm-cli.js i -g npm@latest
             rm -rf node_modules/npm2/
             chmod +x npm.cmd
             chmod +x npm
 
             ./npm.cmd version
-        variants:
-          - windows-compass
-          - windows-compass-community
-          - windows-compass-readonly
-          - windows-compass-isolated
-      - command: shell.exec
-        params:
-          working_dir: src
-          script: |
-            set -ev
+
             curl -fs \
               -o "signtool.exe" \
               --url "https://s3.amazonaws.com/boxes.10gen.com/build/signtool.exe"
             rm -f node_modules/electron-winstaller/vendor/signtool.exe
             chmod +x signtool.exe
+
         variants:
           - windows-compass
           - windows-compass-community
@@ -380,7 +492,7 @@ tasks:
         params:
           working_dir: src
           script: |
-            set -ev
+            set -e
             yum localinstall -y http://mirror.centos.org/centos/7/os/x86_64/Packages/libsecret-0.18.5-2.el7.x86_64.rpm
             yum localinstall -y http://mirror.centos.org/centos/7/os/x86_64/Packages/libsecret-devel-0.18.5-2.el7.x86_64.rpm
         variants:
@@ -392,19 +504,20 @@ tasks:
         params:
           working_dir: src
           script: |
-            set -ev
+            set -e
             sudo apt-get install -y libsecret-1-dev
         variants:
           - ubuntu-compass
           - ubuntu-compass-community
           - ubuntu-compass-readonly
           - ubuntu-compass-isolated
-      - func: 'configure'
+      - func: 'prepare'
       - func: 'install'
-      - command: expansions.update
-        params:
-          file: src/expansions.yml
-      - func: 'build'
+      - func: 'configure'
+      - func: 'verify'
+      - func: 'test'
+      - func: 'package'
+      - func: 'publish'
       - func: 'save windows artifacts'
         variants:
           - windows-compass
@@ -430,9 +543,26 @@ tasks:
           - rhel-compass-readonly
           - rhel-compass-isolated
 
-  #######################################
-  #           Buildvariants             #
-  #######################################
+      # - func: 'save rhel artifacts'
+      #   <<: *rhel-variants
+
+# variables:
+#   - &ubuntu-variants
+#     - variants:
+#       - ubuntu-compass
+#       - ubuntu-compass-community
+#       - ubuntu-compass-readonly
+#       - ubuntu-compass-isolated
+#   - &rhel-variants
+#     - variants:
+#       - rhel-compass
+#       - rhel-compass-community
+#       - rhel-compass-readonly
+#       - rhel-compass-isolated
+
+#######################################
+#           Buildvariants             #
+#######################################
 buildvariants:
   - name: macos-compass
     display_name: MacOS (Compass)
